### ISSUE TITLE
Potential Additional Data

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#11]
What other data sources might add to our analysis?

Please provide links.

**Comment by acarine** [comment]
Tried again looking for data on remittances but still can't find any raw data.  Found articles on FAO website with statistics but no sources of raw data. http://www.fao.org/3/a-ak405e.pdf (pp32-34 talk about remittances, I've tried going to some of the sources to find raw data but none. )

**Comment by acarine** [comment]
https://www.ifad.org/en/ffr

**Comment by bryceleary** [comment]
We may be able to strengthen our theoretical argument by using an additional piece of data: [depth of food deficit](https://inddex.nutrition.tufts.edu/data4diets/indicator/depth-food-deficit?back=/data4diets/indicators). It can help us look not just how average availability changes, but also how availability is changing specifically for those who don't have enough.

**Comment by bryceleary** [comment]
Food depth added, no additional variables will be selected.
