### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#12]
What methods will we use? What is the best regression model? How can a network analysis be integrated? Discuss here.

**Comment by bryceleary** [comment]
Good primer on regressions: https://towardsdatascience.com/introduction-to-bayesian-linear-regression-e66e60791ea7

**Comment by bryceleary** [comment]
Bayesian logistic regression example code:

Average availability:
mc_adesa <- MCMClogit(adesa ~ fdi_net, data = agriculture)
HPDinterval(mc_adesa)

Availability for those in need:
mc_depth <- MCMClogit(depth ~ fdi_net, data = agriculture)
HPDinterval(mc_depth)

**Comment by milikarobbins1** [comment]
Milika's thoughts (not structured, just trying to provide other options!)

Clustering (Agglomerative)
- Start at countries in West Africa as "individuals" with distinct characteristics
- Find which ones are most like each other in terms of flows or nutrition
- End with ways in which all countries in West Africa are all alike

Clustering (Divisive)

- Start at ways in which countries in West Africa are alike
- Split West Africa in ways that groups of countries may be alike
- End with ways in which all countries are unique

___________________________________
**Class example for _Agglomerative_**
italics = notes, not code

pairs(continuousvariable) _<- (country level clustering based on fdi_net)_

dataframename <- dist(continuousvariable1, method = "euclidean")
dataframename %>% round(0)

hag <- hclust(dataframename, method = "complete")
plot (hag) _<-(can call hag something else)_


___________________________________
**Attempt example for _Agglomerative_**

italics = notes, not code

pairs(fdi_net)

agriculture <- dist(fdi_net, method = "euclidean")
agriculture %>% round(0)

agrglom <- hclust(agricutlure, method = "complete")
plot (agrclom)

_____________________________________

Outside resource: https://www.statmethods.net/advstats/cluster.html

**Comment by bryceleary** [comment]
PCA allows us to identify the strongest explanatory variables, and perhaps remove any which are not having much of an effect.

**Comment by acarine** [comment]
I like PCA idea.  https://www.datacamp.com/community/tutorials/pca-analysis-r

**Comment by bryceleary** [comment]
Completed.
