### ISSUE TITLE
Trade Data

### ISSUE THREAD

**Issue by ZeinabouBaraze** [bryceleary/DSIFinal#13]
The agricultural trade data available on FAO is only for year 2017. We will need to find a new data which covers the years 2000 to 2017.

**Comment by bryceleary** [comment]
https://www.trademap.org/tradestat/Product_SelCountry_TS.aspx?nvpm=1%7c204%7c%7c%7c%7cTOTAL%7c%7c%7c2%7c1%7c1%7c1%7c2%7c1%7c1%7c1%7c

http://www.intracen.org/itc/market-info-tools/statistics-import-country-product/

https://libguides.princeton.edu/trade/multinational

https://subjectguides.library.american.edu/ITD

**Comment by acarine** [comment]
https://www.ifpri.org/publications?sm_content_subtype_to_terms=5&sort_by=ds_year&f%5B0%5D=sm_content_subtype_to_terms%3D1&f%5B1%5D=sm_content_subtype_to_terms%3A5605&f%5B2%5D=sm_topics%3Anode%3A12&f%5B3%5D=sm_location%3Anode%3A12081&f%5B4%5D=sm_topics%3Anode%3A12072

**Comment by acarine** [comment]
Added this data in the folder, they are Import/Export data for West Africa from 1990-2018.... I think we could possibly pull it off with this.  Let's discuss this in the morning. 

http://www.fao.org/faostat/en/#data/QI

**Comment by ZeinabouBaraze** [comment]
thank you for the links

**Comment by ZeinabouBaraze** [comment]
The new data have been added and cleaned
