### ISSUE TITLE
Scale Variables

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#14]
Ensure variables are on easily understood, and comparable scales.

**Comment by milikarobbins1** [comment]
World Bank advice: https://datahelpdesk.worldbank.org/knowledgebase/articles/114946-how-can-i-rescale-a-series-to-a-different-base-yea

Duke advice: https://people.duke.edu/~rnau/411infla.htm

**Comment by milikarobbins1** [comment]
Resource for scaling monetary values in R: https://www.pluralsight.com/guides/normalizing-data-r

**Comment by milikarobbins1** [comment]
Calculation using CPIs year over year: https://www.census.gov/topics/income-poverty/income/guidance/current-vs-constant-dollars.html

We will use this to adjust the 2010 USD values to 2016 for consistency across the dataset.

**Comment by milikarobbins1** [comment]
The adjustment has been made to the FDI dataset.
