### ISSUE TITLE
Data wrangling steps section

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#5]
Describe the data wrangling process and section both via .R comments and a written section.

**Comment by bryceleary** [comment]
@milikarobbins1 Let's chat tomorrow about merging the datasets, and how we want to deal with the 'year' variable. Then we can easily get this written up.

**Comment by milikarobbins1** [comment]
I am going to create a 'codebook' to cover each variable's final state in a table format. This can go in our appendix.

**Comment by bryceleary** [comment]
Completed and added to RMD.
