### ISSUE TITLE
Questions for Professor Moore & Simon

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#6]
Professor Moore and Simon,
We have a few questions we are looking for clarification on. We are happy to touch base with you in class, instead of having them answered here, but wanted to practice using Github and the issues system.

What is the intended length of the final data analysis paper? What should the length of the sections be?
What citation style should be used?
What are the grading criteria?
Are visualizations required? If so, is there a minimum amount or type?
How long are the presentations? Should it cover the same items as the paper?

**Comment by ryantmoore** [comment]
@bryceleary, et _al_.:

1. What is the intended length of the final data analysis paper? What should the length of the sections be?

I expect there to be some variety, depending on whether the focus is substantive or methodological.  Do not feel the need to add an extraneous literature review, but provide us enough context to a) understand, b) be motivated about the importance of the question, and c) comprehend the intellectual debate you participate in.  It's hard to imagine you could do this, and describe your methods, results, and interpretations in under 5 pages.  There's no "20-page minimum" or anything like that, though.  Quality over quantity.

2. What citation style should be used?

Any, so long as it's reasonable, consistent, and used in an academic field.  I suggest the substantive field that you want to contribute to.

3. What are the grading criteria?

We'll evaluate whether the "Work Product" components are included, well-conceived, and well-implemented.  Strength in one area can compensate for relative weakness in another.  

4. Are visualizations required? If so, is there a minimum amount or type?

No, but encouraged.  They can add a great deal to the reader's ability to understand your problem or findings.  

5. How long are the presentations? Should it cover the same items as the paper?

With seven groups, we envision about 20-25 minutes per group.  About half to two-thirds of this can be presentation, with ample time for questions and discussion from instructors and colleagues.  We'll  repost the final assignment document.

**Comment by bryceleary** [comment]
Professor @ryantmoore thank you for the response, these are helpful guidelines.
