### ISSUE TITLE
Possibly incorrect years in nutrition data

### ISSUE THREAD

**Issue by bryceleary** [bryceleary/DSIFinal#8]
@ZeinabouBaraze the nutrition data in the repo is from 2014-2017. Did we shorten the timeframe from starting in 2000 to start in 2014? I did not take good notes today!

**Comment by ZeinabouBaraze** [comment]
The data on nutrition goes up to 2014 only. So we will maybe have to look at other data or use the agriculture data up to 2014 as well.
